workflows:
  build-android-and-ios:
    name: Android + iOS Build
    max_build_duration: 120
    environment:
      flutter: 3.29.0
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
      cancel_previous_builds: true      
    scripts:
      - name: Show Flutter version
        script: flutter --version

      - name: Set up local.properties for Android
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

      - name: Get Flutter packages
        script: flutter pub get

      - name: Build Android APK
        script: flutter build apk --release

      - name: Build iOS IPA (unsigned)
        script: flutter build ipa --debug --no-codesign

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - flutter_drive.log


# workflows:
#   android-build-only:
#     name: Android Build Only
#     max_build_duration: 120
#     environment:
#       flutter: 3.29.0
#     triggering:
#       events:
#         - push
#       branch_patterns:
#         - pattern: main
#           include: true
#       cancel_previous_builds: true
#     scripts:
#       - name: Show Flutter version
#         script: flutter --version

#       - name: Set up local.properties
#         script: |
#           echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

#       - name: Get Flutter packages
#         script: flutter pub get

#       - name: Build APK
#         script: flutter build apk --release

#     artifacts:
#       - build/**/outputs/**/*.aab
#       - build/**/outputs/**/*.apk
#       - build/**/outputs/**/mapping.txt
#       - flutter_drive.log

#   ios-build-only:
#     name: iOS Build Only
#     environment:
#       flutter: 3.29.0
#       xcode: latest
#       cocoapods: default
#     scripts:
#       - name: Install Flutter packages
#         script: flutter pub get

#       - name: Build IPA (unsigned)
#         script: flutter build ipa --debug --no-codesign

#     artifacts:
#       - build/ios/ipa/*.ipa



# workflows:
#   android-workflow:
#     name: Android Workflow
#     max_build_duration: 120
#     environment:
#       # android_signing:
#       #   - joesAndroidKeystore
#       # groups:
#       #   - google_play
#       # vars:
#       #   PACKAGE_NAME: "com.joesjewelry.crm.app"
#       #   GOOGLE_PLAY_TRACK: production
#       flutter: 3.29.0
#     triggering:
#       events:
#         - push
#       branch_patterns:
#         - pattern: main
#           include: true
#       cancel_previous_builds: true
#     scripts:
#       - name: Show Flutter version
#         script: |
#           flutter --version
 
#       - name: Set up local.properties
#         script: |
#           echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

#       - name: Get Flutter packages
#         script: |
#           flutter packages pub get
          
#       - name: Build APK
#         script: |
#           flutter build apk --release
#       # - name: Build AAB with Flutter
#       #   script: |
#       #     BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))      
#       #     flutter build appbundle --release \
#       #       --build-name=1.0.$BUILD_NUMBER \
#       #       --build-number=$BUILD_NUMBER
#     artifacts:
#       - build/**/outputs/**/*.aab
#       - build/**/outputs/**/*.apk
#       - build/**/outputs/**/mapping.txt
#       - flutter_drive.log
#         # publishing:
#         #   email:
#         #     recipients:
#         #       - ajay.m@infozzle.com
#         #     notify:
#         #       success: true
#         #       failure: false
#         #   google_play:
#         #     credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
#         #     track: $GOOGLE_PLAY_TRACK




# workflows:
#   ios-release:
#     name: iOS Release to TestFlight
#     environment:
#       flutter: 3.29.0
#       xcode: latest
#       cocoapods: default
#       vars:
#         BUNDLE_ID: "com.joesjewelry.crm.app
#       groups:
#         - app_store_credentials
#     scripts:
#       - name: Set up keychain and code signing
#         script: |
#           keychain initialize
#           app-store-connect fetch-signing-files "$BUNDLE_ID" \
#             --type IOS_APP_STORE \
#             --create \
#             --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
#             --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
#             --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"
#           keychain add-certificates
#       - name: Get Flutter packages
#         script: flutter pub get
#       - name: Build iOS app
#         script: flutter build ipa --release
#     artifacts:
#       - build/ios/ipa/*.ipa
#     publishing:
#       app_store_connect:
#         auth: integration
#         submit_to_testflight: true
